import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const Legal = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 py-12 sm:py-16">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4" />
          <span className="font-body text-sm">Back to Home</span>
        </Link>

        <h1 className="font-display text-4xl sm:text-5xl text-foreground mb-8">
          Legal Disclaimer & Disclosures
        </h1>

        <div className="space-y-8 font-body text-muted-foreground">
          <section>
            <h2 className="font-display text-2xl text-foreground mb-4">1. No Affiliation With GameStop</h2>
            <p className="leading-relaxed">
              This project is a fan-created, community-driven initiative.
            </p>
            <p className="leading-relaxed mt-4">
              Buck the Bunny and all related characters, likenesses, names, and references are the intellectual property of GameStop Corp. This project does not claim ownership of Buck the Bunny and is not affiliated with, endorsed by, sponsored by, or associated with GameStop Corp. in any way.
            </p>
            <p className="leading-relaxed mt-4">
              All references to Buck the Bunny are used solely for expressive, artistic, and community-driven purposes.
            </p>
          </section>

          <hr className="border-border" />

          <section>
            <h2 className="font-display text-2xl text-foreground mb-4">2. Artist Involvement & Compensation</h2>
            <p className="leading-relaxed">
              The original Buck the Bunny character was designed by artist Dustin Clause Harder.
            </p>
            <p className="leading-relaxed mt-4">
              This project acknowledges and celebrates Dustin Clause Harder as the original creator of Buck the Bunny. Any creator fees or artist-related compensation generated by this project are directed to Dustin Clause Harder as a gesture of recognition and support for his original creative contribution.
            </p>
            <p className="leading-relaxed mt-4">
              Nothing in this project grants ownership, licensing rights, or intellectual property rights to any party.
            </p>
          </section>

          <hr className="border-border" />

          <section>
            <h2 className="font-display text-2xl text-foreground mb-4">3. No Ownership or Licensing Claims</h2>
            <p className="leading-relaxed">
              This project does not claim to own, license, or control any intellectual property associated with Buck the Bunny or GameStop.
            </p>
            <p className="leading-relaxed mt-4">
              All trademarks, service marks, logos, and intellectual property referenced remain the property of their respective owners.
            </p>
          </section>

          <hr className="border-border" />

          <section>
            <h2 className="font-display text-2xl text-foreground mb-4">4. Nature of the Token</h2>
            <p className="leading-relaxed">
              This project involves a blockchain-based cryptocurrency token (a "memecoin") created for entertainment, cultural expression, and community participation.
            </p>
            <p className="leading-relaxed mt-4">The token is not:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 ml-4">
              <li>A security</li>
              <li>An investment contract</li>
              <li>A share of ownership</li>
              <li>A guarantee of profit</li>
              <li>A promise of future value</li>
            </ul>
            <p className="leading-relaxed mt-4">
              There is no expectation of profit derived from the efforts of others.
            </p>
          </section>

          <hr className="border-border" />

          <section>
            <h2 className="font-display text-2xl text-foreground mb-4">5. No Financial Advice</h2>
            <p className="leading-relaxed">
              Nothing on this website or associated channels constitutes financial, legal, tax, or investment advice.
            </p>
            <p className="leading-relaxed mt-4">
              You are solely responsible for any decisions you make regarding cryptocurrency or digital assets. Always conduct your own research and consult qualified professionals if needed.
            </p>
          </section>

          <hr className="border-border" />

          <section>
            <h2 className="font-display text-2xl text-foreground mb-4">6. Risk Acknowledgement</h2>
            <p className="leading-relaxed">
              Cryptocurrency assets are highly volatile and speculative.
            </p>
            <p className="leading-relaxed mt-4">
              By interacting with this project, you acknowledge and accept that you may lose some or all of any funds you choose to use.
            </p>
            <p className="leading-relaxed mt-4">
              Participation is entirely at your own risk.
            </p>
          </section>

          <hr className="border-border" />

          <section>
            <h2 className="font-display text-2xl text-foreground mb-4">7. Limitation of Liability</h2>
            <p className="leading-relaxed">
              To the maximum extent permitted by law, the project creators, contributors, and community participants shall not be liable for any direct, indirect, incidental, or consequential damages arising from your participation in or interaction with this project.
            </p>
          </section>

          <hr className="border-border" />

          <section>
            <h2 className="font-display text-2xl text-foreground mb-4">8. Jurisdiction & Changes</h2>
            <p className="leading-relaxed">
              This disclaimer may be updated at any time without notice.
            </p>
            <p className="leading-relaxed mt-4">
              By using this site or interacting with this project, you agree to these terms.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span className="font-body text-sm">Back to Home</span>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Legal;
